package com.example.medicalarzi.component;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.medicalarzi.util.MedicalArziConstants;
import com.example.medicalarzi.view.SimpleLoginView;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.themes.Reindeer;

public class ArziHeaderComponent extends CustomComponent implements ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 *
	 */
	private static final long serialVersionUID = 3413881598466386600L;

	public static Logger logger = LogManager.getLogger(ArziHeaderComponent.class);

	private HorizontalLayout mainLayout;
	private Label headerTitle;
	private Embedded banner;
	private Label loggedInUserName;
	private Button logout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ArziHeaderComponent() {
		buildMainLayout();
		mainLayout.setStyleName("banner");
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	private HorizontalLayout buildMainLayout() {
		// top-level component properties
		setSizeFull();

		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();

		// headerTitle
		headerTitle = new Label();
		headerTitle.setValue("Medical Arzi");
		headerTitle.setImmediate(false);
		headerTitle.setStyleName("banner-title");
		mainLayout.addComponent(headerTitle);
		mainLayout.setComponentAlignment(headerTitle, Alignment.MIDDLE_LEFT);
		mainLayout.setExpandRatio(headerTitle, 2.0f);

		// loggedInUserName
		loggedInUserName = new Label();
		loggedInUserName.setId(MedicalArziConstants.HEADER_LOGGED_IN_PTNT_NAME);
		loggedInUserName.setImmediate(false);
		mainLayout.addComponent(loggedInUserName);
		mainLayout.setComponentAlignment(loggedInUserName, Alignment.MIDDLE_RIGHT);
		mainLayout.setExpandRatio(loggedInUserName, 0.5f);

		// logout
		logout = new Button(new ThemeResource("img/logout-button.png"));
		logout.setId(MedicalArziConstants.HEADER_LOGOUT_BUTTON_ID);
		logout.addClickListener(this);
		logout.setImmediate(true);
		logout.setStyleName(Reindeer.BUTTON_LINK);
		mainLayout.addComponent(logout);
		mainLayout.setComponentAlignment(logout, Alignment.MIDDLE_RIGHT);
		mainLayout.setExpandRatio(logout, 1.0f);

		// headerTitle
		banner = new Embedded();
		banner.setSource(new ThemeResource("img/moula-banner.png"));
		mainLayout.addComponentAsFirst(banner);
		mainLayout.setExpandRatio(banner, 1.0f);
		mainLayout.setComponentAlignment(banner, Alignment.TOP_LEFT);

		return mainLayout;
	}

	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getButton().equals(logout)) {
			 // "Logout" the patient
           getSession().setAttribute(MedicalArziConstants.SESS_ATTR_PTNT_ITS_NUM, null);

           // Refresh this view, should redirect to login view
           getUI().getNavigator().navigateTo(SimpleLoginView.NAME);
		}		
	}

}
