package com.example.medicalarzi.component;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.medicalarzi.util.MedicalArziConstants;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

public class CustomFormComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = -3409550163727434662L;
	
	public static Logger logger = LogManager.getLogger(CustomFormComponent.class);
	
	private HorizontalLayout mainLayout;

	private VerticalLayout leftLayout;
	
	private FormLayout leftFormLayout;
	
	private VerticalLayout rightLayout;

	private FormLayout rightFormLayout;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CustomFormComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	private HorizontalLayout buildMainLayout() {
		// top-level component properties
		setSizeFull();
		
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		
		// leftLayout
		leftLayout = buildLeftLayout();
		mainLayout.addComponent(leftLayout);
		mainLayout.setExpandRatio(leftLayout, 1.0f);
		
		// rightLayout
		rightLayout = buildRightLayout();
		mainLayout.addComponent(rightLayout);
		mainLayout.setExpandRatio(rightLayout, 1.0f);
		
		return mainLayout;
	}

	private VerticalLayout buildLeftLayout() {
		// common part: create layout
		leftLayout = new VerticalLayout();
		leftLayout.setImmediate(false);
		leftLayout.setWidth("100.0%");
		leftLayout.setHeight("100.0%");
		leftLayout.setMargin(false);
		
		// leftFormLayout
		leftFormLayout = new FormLayout();
		leftFormLayout.setId(MedicalArziConstants.CUSTOM_FORM_LEFTFORM_LAYOUT_ID);
		leftLayout.addComponent(leftFormLayout);
		
		return leftLayout;
	}

	private VerticalLayout buildRightLayout() {
		// common part: create layout
		rightLayout = new VerticalLayout();
		rightLayout.setImmediate(false);
		rightLayout.setWidth("100.0%");
		rightLayout.setHeight("100.0%");
		rightLayout.setMargin(false);
		
		// rightFormLayout
		rightFormLayout = new FormLayout();
		rightFormLayout.setId(MedicalArziConstants.CUSTOM_FORM_RIGHTFORM_LAYOUT_ID);
		rightLayout.addComponent(rightFormLayout);
		
		return rightLayout;
	}

}
