package com.example.medicalarzi.component;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class SearchComponent extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3746920156025742346L;

	public static Logger logger = LogManager.getLogger(SearchComponent.class);

	// View Layouts and Components
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SearchComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private void buildMainLayout() {
		// top-level component properties
		setSizeFull();

		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();

	}

}
